added docker-build-push github action
LN-Zap/docker-lnd pull request #8
Opened 2021-05-24 12:56 UTC by RonaldCrb

This PR builds and push the lnd image to docker-hub based on any push to a branch with a name like => `0.*` ; 

for this action to work, it requires the following secrets to be configured in the repo.  

1. `DOCKERHUB_USERNAME`
2. `DOCKERHUB_TOKEN`

2021-05-24 13:07 UTC, mrfelton requested changes

2021-05-24 13:07 UTC, mrfelton commented on .github/workflows/docker-build-push.yaml
> +          tags: user/app:latest
Presumably we need to set this to the correct image name here?

2021-05-24 13:17 UTC, RonaldCrb commented on .github/workflows/docker-build-push.yaml
> +          tags: user/app:latest
ahhh youre right. i forgot to change that

2021-05-24 13:19 UTC, mrfelton commented
Can we integrate this with tags too @RonaldCrb  such that pushing a github tag triggers a build and creation of image with said tag?

2021-05-24 13:27 UTC, RonaldCrb commented
thats a great idea, i didnt thought about the tags in this repo because i saw there were none. i will look into it, thanks for the quick feedback!

2021-05-24 13:28 UTC, mrfelton commented
> i didnt thought about the tags in this repo because i saw there were none

Yeah, that's because this repo has not had the tlc that it needs to date. Today is a good day to change that :)

2021-05-24 15:30 UTC, RonaldCrb commented
> Looks good!
> 
> Only thing we need before merge is a test that makes sure the build is in good state before publish - something as simple as `lncli --version` (expecting a match of whatever version we're building) should suffice.

im investigating how to achieve this since the action im proposing builds and pushes the image in a single motion

2021-05-25 09:15 UTC, mrfelton commented
Another thing that would be very useful would be to also build and push a debug version of the image. Meaning, a version that bundles the debug binaries rather than the production ones.

You can see how to do this in the branch https://github.com/LN-Zap/docker-lnd/tree/0.10.x-beta-debug where I did it once before. The key think is to copy the debug binaries into the container rather than the normal ones, as per https://github.com/LN-Zap/docker-lnd/blob/0.10.x-beta-debug/Dockerfile#L22-L23

This is sometimes needed in order to resolve issues like the one described in https://github.com/LN-Zap/zap-middleware/issues/2460 (one way to resolve these are to run a debug version of lnd - which adds the `abandonchannel` rpc - and then to call that).

Not sure if you want to handle that here or in a follow up PR though.

2021-05-27 16:00 UTC, RonaldCrb commented
this is ready for review, 

added:

1. build the image with each release
2. build both the normal and debug images and tag them with the release tag
3. smoke test on both images using `lncli --version` and comparing it to the release tag
4. push the images to dockerhub

there is an outstanding point concerning the update of the readme file on the dockerhub page, so i did commented that section of the pipeline definition until we can provide the `zap-ci` user with privileges to update the repo metadata and the readme page of the images

2021-05-27 17:35 UTC, szollo commented on .github/scripts/smoke-test.sh
> +  exit 42
Is there a reasoning why this is `exit 42` instead of a normal `exit 1`?

2021-05-28 06:23 UTC, RonaldCrb commented on .github/scripts/smoke-test.sh
> +  exit 42
there is no objective reasoning behind that. in any case i have changed it and also added meaningful messages for success and error.

2021-05-28 16:20 UTC, szollo approved these changes
LGTM!

So I guess our new workflow to build lnd images in this repo from now on will be to tag each new release using GitHub Releases.

2021-05-28 17:41 UTC, RonaldCrb commented
> LGTM!
> 
> So I guess our new workflow to build lnd images in this repo from now on will be to tag each new release using GitHub Releases.

correct, each release tag becomes the docker image tag, so in an ideal situation, one will create a branch, compile the image locally to make sure the desired result is achieved, then create a release tag. once the release is published, the action will trigger. and the image is actually pushed to dockerhub.

2021-05-28 17:49 UTC, merged